### ISSUE TITLE
Change log-in page styles

### ISSUE THREAD

**Issue by DAreRodz** [frontity/ads-form#43]
Child of #39

**Comment by luisherranz** [comment]
In my opinion styling this shouldn't have any priority. Only us and AZ is going to use it and this first work of styling should be focused only on UI clarity and not on aesthetics. We can do another aesthetics work afterwards if needed.

cc: @poliuk

**Comment by Poliuk** [comment]
It was me who told @darerodz to also take a look to this screen. I'm not really confident letting customers use a dashboard with screens in plain HTML. I don't want to spend more than 1 day with the whole redesign but still I think we need something better to what we have. And it has to be ready for the new customers before they arrive, otherwise this will block the integrations.

Anyways we can discuss the efforts we should put here.

**Comment by Poliuk** [comment]
I like this approach @luisherranz It looks like just adding something like mini.css will style everything enough, so we can focus on the clarity of the ads form itself.

**Comment by luisherranz** [comment]
Ok, I'll take a quick look.

**Comment by luisherranz** [comment]
It looks like `mini.css` works fine that way.
